#!/data/data/com.termux/files/usr/bin/bash
set -e -u

SCRIPTNAME=termux-camera-photo
show_usage () {
    echo "Usage: $SCRIPTNAME [-e] [-o] [-s] [-f filename]"
    echo "Take a photo and save it to a file in JPEG format."
    echo ""
    echo "  -f Use specified file"
    echo "  -c Copy results to clipboard"
    echo "  -e Echo results"
    echo "  -s Share detected text"
    echo "  -o Open detected URL on browser"
    echo ""
    exit 0
}

FILE=''
COPY=false
ECHO=false
OPEN=false
SHARE=false
DELETE=false

for i in "$@"
do
    case $i in
        -c|--copy)
            COPY=true
        ;;
        -e|--echo)
            ECHO=true
        ;;
        -o|--open)
            OPEN=true
        ;;
        -s|--share)
            SHARE=true
        ;;
	*)
	    if [ -f "$i" ]; then
	        FILE=$i
	    fi
	;;
    esac
done

if [ "x$FILE" == "x" ]; then
    DELETE=true
    FILE='./barcode.jpg'

    termux-camera-photo -c 0 $FILE
fi

OUTPUT=`zbarimg --quiet --raw "$FILE"`

if [ "x$OUTPUT" != "x" ]; then
    if [ $COPY == true ]; then
        termux-clipboard-set "$OUTPUT"
		termux-toast "Output copied to clipboard"
    elif [ $SHARE == true ]; then
        echo $OUTPUT | termux-share
    elif [ $OPEN == true ]; then
	    termux-open-url "$OUTPUT"
	elif [ $ECHO == true ]; then
        echo $OUTPUT
	else
		termux-toast "$OUTPUT"
    fi
else
    echo "No barcode found"
fi

