#!/data/data/com.termux/files/usr/bin/bash
set -e -u

SCRIPTNAME=ocr-scan
show_usage () {
    echo "Usage: $SCRIPTNAME [-e] [-s] [-f filename]"
    echo "Recognizes text on an image to copy or share results"
    echo ""
    echo "  -f Use specified file"
    echo "  -c Copy results to clipboard"
    echo "  -e Echo results"
    echo "  -s Share detected text"
    echo ""
    exit 0
}

FILE=''
COPY=false
ECHO=false
SHARE=false
DELETE=false

for i in "$@"
do
    case $i in
		-h|--help)
	    	show_usage
		    exit 0
		;;
        -c|--copy)
            COPY=true
        ;;
        -e|--echo)
            ECHO=true
        ;;
        -s|--share)
            SHARE=true
        ;;
	*)
	    if [ -f "$i" ]; then
	        FILE=$i
	    fi
	;;
    esac
done

if [ "x$FILE" == "x" ]; then
    DELETE=true
    FILE='./ocr.jpg'

    termux-camera-photo -c 0 $FILE
fi

tesseract "$FILE" ocr
OUTPUT=`cat ocr.txt`
rm ocr.txt

if [ "x$OUTPUT" != "x" ]; then
    if [ $COPY == true ]; then
        termux-clipboard-set "$OUTPUT"
		termux-toast "Output copied to clipboard"
    elif [ $SHARE == true ]; then
        echo $OUTPUT | termux-share
	elif [ $ECHO == true ]; then
        echo $OUTPUT
	else
		termux-toast "$OUTPUT"
    fi
else
    echo "No text found"
fi

if [ $DELETE == true ]; then
    rm -f $FILE
fi
