#!/data/data/com.termux/files/usr/bin/bash

IP_ADDRESS=`ifconfig wlan0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'`

if [ -z "$PHP_WEB_SERVER_PORT" ]; then
	PHP_WEB_SERVER_PORT=8080
fi

if [ -z "$PHP_WEB_SERVER_ROOT" ]; then
	PHP_WEB_SERVER_ROOT=`pwd`
fi

if [ -z "$1" ] && [ -z "$PHP_WEB_SERVER_ROUTER" ]; then
	PHP_WEB_SERVER_ROUTER="_h5ai/router.php"
elif [ -z "$PHP_WEB_SERVER_ROUTER"]; then
	PHP_WEB_SERVER_ROUTER=$1
fi

echo "Public IP address is $IP_ADDRESS"
php -S "0.0.0.0:${PHP_WEB_SERVER_PORT}" $PHP_WEB_SERVER_ROUTER
